import React, { useState } from 'react';
import { Upload, Sparkles, Copy, Share2, Heart, Zap, RotateCcw } from 'lucide-react';

const DatingProfileOptimizer = () => {
  const [photos, setPhotos] = useState([]);
  const [bio, setBio] = useState('');
  const [loading, setLoading] = useState(false);
  const [profiles, setProfiles] = useState([]);
  const [selectedProfile, setSelectedProfile] = useState(null);
  const [apiKey, setApiKey] = useState('');
  const [showApiModal, setShowApiModal] = useState(false);

  const handlePhotoUpload = (e) => {
    const files = Array.from(e.target.files);
    files.forEach(file => {
      const reader = new FileReader();
      reader.onload = (event) => {
        setPhotos(prev => [...prev, {
          id: Date.now() + Math.random(),
          src: event.target.result,
          file: file
        }]);
      };
      reader.readAsDataURL(file);
    });
  };

  const removePhoto = (id) => {
    setPhotos(prev => prev.filter(p => p.id !== id));
  };

  const generateProfiles = async () => {
    if (!apiKey) {
      setShowApiModal(true);
      return;
    }

    if (!bio.trim()) {
      alert('Please enter your current dating bio!');
      return;
    }

    setLoading(true);
    try {
      const prompt = `You are an expert dating profile writer who creates viral, authentic, and irresistible dating bios.

Current Bio: "${bio}"

Generate exactly 5 different dating profile versions. Each should:
1. Be authentic and genuine (not generic AI)
2. Have a unique angle/vibe
3. Include specific details that spark conversation
4. Be between 100-200 characters
5. Work for dating apps like Tinder, Hinge, Bumble

For each profile, also include:
- A "Vibe" label (e.g., "Mysterious", "Funny", "Ambitious", "Chill", "Romantic")
- Why this version works (1 sentence)

Format as JSON:
{
  "profiles": [
    {
      "vibe": "Vibe Name",
      "bio": "The bio text",
      "why_it_works": "Why this works"
    }
  ]
}

Make them feel fresh, unique, and like they could genuinely belong to different versions of the same person. The goal is to get more matches.`;

      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
        },
        body: JSON.stringify({
          model: 'claude-opus-4-1',
          max_tokens: 1500,
          messages: [
            {
              role: 'user',
              content: prompt
            }
          ]
        })
      });

      if (!response.ok) {
        throw new Error('API error: ' + response.statusText);
      }

      const data = await response.json();
      const content = data.content[0].text;
      
      // Parse JSON from response
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        setProfiles(parsed.profiles);
        setSelectedProfile(0);
      }
    } catch (error) {
      alert('Error: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    alert('Copied to clipboard! 🔥');
  };

  const shareProfile = () => {
    if (!selectedProfile !== null && profiles[selectedProfile]) {
      const text = `Check out this dating profile: "${profiles[selectedProfile].bio}" - Generated by Dating Profile Optimizer`;
      if (navigator.share) {
        navigator.share({ title: 'Dating Profile', text });
      } else {
        copyToClipboard(text);
      }
    }
  };

  const reset = () => {
    setPhotos([]);
    setBio('');
    setProfiles([]);
    setSelectedProfile(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-pink-500 via-red-500 to-orange-500 p-6">
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Heart className="w-10 h-10 text-white fill-white" />
            <h1 className="text-4xl font-black text-white">Profile Optimizer</h1>
            <Sparkles className="w-10 h-10 text-yellow-300" />
          </div>
          <p className="text-white text-lg opacity-90">Transform your dating bio into a match magnet 🔥</p>
        </div>

        {/* API Key Modal */}
        {showApiModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl p-8 max-w-md w-full">
              <h2 className="text-2xl font-bold mb-4">Add Your API Key</h2>
              <p className="text-gray-600 mb-4">Get your free Anthropic API key at:</p>
              <a href="https://console.anthropic.com/keys" target="_blank" rel="noopener noreferrer" 
                 className="text-blue-600 underline mb-6 block">console.anthropic.com/keys</a>
              <input
                type="password"
                placeholder="sk-ant-..."
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg mb-4"
              />
              <button
                onClick={() => setShowApiModal(false)}
                className="w-full bg-gradient-to-r from-pink-500 to-red-500 text-white py-2 rounded-lg font-bold hover:shadow-lg transition"
              >
                Save & Continue
              </button>
            </div>
          </div>
        )}

        {/* Main Card */}
        <div className="bg-white rounded-3xl shadow-2xl p-8 mb-6">
          
          {/* Photos Section */}
          <div className="mb-8">
            <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Upload className="w-5 h-5" /> Your Photos
            </h2>
            <div className="grid grid-cols-3 gap-4 mb-4">
              {photos.map(photo => (
                <div key={photo.id} className="relative group">
                  <img src={photo.src} alt="preview" className="w-full h-24 object-cover rounded-lg" />
                  <button
                    onClick={() => removePhoto(photo.id)}
                    className="absolute top-1 right-1 bg-red-500 text-white w-6 h-6 rounded-full opacity-0 group-hover:opacity-100 transition"
                  >
                    ×
                  </button>
                </div>
              ))}
              {photos.length < 5 && (
                <label className="border-2 border-dashed border-gray-300 rounded-lg h-24 flex items-center justify-center cursor-pointer hover:border-pink-500 transition">
                  <input type="file" multiple accept="image/*" onChange={handlePhotoUpload} className="hidden" />
                  <span className="text-gray-400">+ Add</span>
                </label>
              )}
            </div>
            <p className="text-sm text-gray-500">{photos.length}/5 photos</p>
          </div>

          {/* Bio Section */}
          <div className="mb-8">
            <h2 className="text-xl font-bold mb-4">Your Current Bio</h2>
            <textarea
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              placeholder="Paste your current dating bio here... (e.g., 'Coffee lover, dog dad, always up for adventure')"
              className="w-full px-4 py-3 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-pink-500 h-24"
            />
            <p className="text-sm text-gray-500 mt-2">{bio.length} characters</p>
          </div>

          {/* Generate Button */}
          <button
            onClick={generateProfiles}
            disabled={loading}
            className="w-full bg-gradient-to-r from-pink-500 to-red-500 text-white py-4 rounded-xl font-bold text-lg hover:shadow-lg transition disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <Zap className="w-5 h-5" />
            {loading ? 'Generating Your Profiles...' : 'Make Me Viral 🔥'}
          </button>
        </div>

        {/* Results */}
        {profiles.length > 0 && (
          <div className="bg-white rounded-3xl shadow-2xl p-8">
            <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-yellow-500" />
              Your 5 Viral Profiles
            </h2>

            {/* Profile Selector */}
            <div className="flex gap-2 mb-6 overflow-x-auto pb-2">
              {profiles.map((profile, idx) => (
                <button
                  key={idx}
                  onClick={() => setSelectedProfile(idx)}
                  className={`px-4 py-2 rounded-full font-bold whitespace-nowrap transition ${
                    selectedProfile === idx
                      ? 'bg-gradient-to-r from-pink-500 to-red-500 text-white'
                      : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }`}
                >
                  {profile.vibe}
                </button>
              ))}
            </div>

            {/* Selected Profile Display */}
            {selectedProfile !== null && profiles[selectedProfile] && (
              <div className="bg-gradient-to-br from-pink-50 to-orange-50 rounded-2xl p-6 mb-6">
                <div className="mb-4">
                  <span className="inline-block bg-gradient-to-r from-pink-500 to-red-500 text-white px-4 py-1 rounded-full text-sm font-bold mb-3">
                    {profiles[selectedProfile].vibe}
                  </span>
                  <p className="text-2xl font-bold text-gray-900 mb-4">
                    {profiles[selectedProfile].bio}
                  </p>
                  <p className="text-gray-700 mb-4">
                    <span className="font-bold">💡 Why it works:</span> {profiles[selectedProfile].why_it_works}
                  </p>
                </div>

                <div className="flex gap-3">
                  <button
                    onClick={() => copyToClipboard(profiles[selectedProfile].bio)}
                    className="flex-1 bg-blue-500 hover:bg-blue-600 text-white py-2 rounded-lg font-bold flex items-center justify-center gap-2 transition"
                  >
                    <Copy className="w-5 h-5" /> Copy
                  </button>
                  <button
                    onClick={shareProfile}
                    className="flex-1 bg-green-500 hover:bg-green-600 text-white py-2 rounded-lg font-bold flex items-center justify-center gap-2 transition"
                  >
                    <Share2 className="w-5 h-5" /> Share
                  </button>
                </div>
              </div>
            )}

            {/* All Profiles List */}
            <div className="space-y-3">
              {profiles.map((profile, idx) => (
                <div key={idx} className="bg-gray-50 p-4 rounded-lg">
                  <p className="font-bold text-gray-900 mb-1">{profile.vibe}</p>
                  <p className="text-gray-700 mb-2">"{profile.bio}"</p>
                  <p className="text-sm text-gray-600">💡 {profile.why_it_works}</p>
                </div>
              ))}
            </div>

            {/* Reset Button */}
            <button
              onClick={reset}
              className="w-full mt-6 bg-gray-200 hover:bg-gray-300 text-gray-700 py-2 rounded-lg font-bold flex items-center justify-center gap-2 transition"
            >
              <RotateCcw className="w-5 h-5" /> Generate New Profiles
            </button>
          </div>
        )}

        {/* Footer */}
        <div className="text-center mt-8 text-white">
          <p className="text-sm opacity-80">✨ Powered by Claude AI</p>
          <p className="text-xs opacity-60 mt-2">Your API key is never stored. All processing is private.</p>
        </div>
      </div>
    </div>
  );
};

export default DatingProfileOptimizer;